#!/bin/sh
make defuse_defconfig
make -j16 && cp -a $(find . -name *.ko -print) ../initramfs-gtg/lib/modules/ && make -j16
# adb shell reboot download
# sleep 5
# heimdall flash --kernel arch/arm/boot/zImage
